wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    code_path: code/ppo.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.5
    start_time: 1705042440
    t:
      1:
      - 1
      2:
      - 1
      4: 3.9.5
      5: 0.12.1
      8:
      - 5
cuda:
  desc: null
  value: true
exp_name:
  desc: null
  value: ppo
gym_id:
  desc: null
  value: CartPole-v1
learning_rate:
  desc: null
  value: 0.00025
seed:
  desc: null
  value: 1
torch_deterministic:
  desc: null
  value: true
total_timesteps:
  desc: null
  value: 25000
track:
  desc: null
  value: true
wandb_entity:
  desc: null
  value: null
wandb_project_name:
  desc: null
  value: cleanRL
